### ISSUE TITLE
return exit code 1 on failing to download from aps

### ISSUE THREAD

**Issue by jhpoelen** [Planteome/samara#62]
Currently, exit code 0 (=success) is returned when the main aps disease page fails to download:

```
[https://www.apsnet.org/edcenter/resources//commonnames/Pages/default.aspx] downloading ...[https://www.apsnet.org/edcenter/resources//commonnames/Pages/default.aspx] download failed because of:
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
```

Suggested is to return exit code 1 when unexpected downloads error happen.

**Comment by jhpoelen** [comment]
By returning exit code 1 (non-success), the jenkins job at https://build.berkeleybop.org/view/Planteome/job/extract-apsnet-diseases can mark a scrape as failed.

fyi @marieALaporte

**Comment by jhpoelen** [comment]
Now, exit code 1 is returned when a download fails. 

```shell
$ java -jar target/scala-2.12/samara-assembly-0.1.10.jar scrape apsnet
disease_name	source_taxon_verbatim_name	source_taxon_name	source_taxon_id	interaction_type_label	interaction_type_id	target_taxon_verbatim_name	target_taxon_name	target_taxon_id	target_part_name	target_part_id	source_citation	source_url	source_accessed_at
[https://www.apsnet.org/edcenter/resources//commonnames/Pages/default.aspx] downloading ...[https://www.apsnet.org/edcenter/resources//commonnames/Pages/default.aspx] download failed because of:
java.net.UnknownHostException: www.apsnet.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:571)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:548)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:235)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:224)
	at org.planteome.samara.ResourceUtil.get(ResourceUtil.scala:17)
	at org.planteome.samara.ResourceUtil.get$(ResourceUtil.scala:11)
	at org.planteome.samara.ScraperApsnet$.get(ScraperApsnet.scala:11)
	at org.planteome.samara.ResourceUtil.getTry(ResourceUtil.scala:24)
	at org.planteome.samara.ResourceUtil.getTry$(ResourceUtil.scala:22)
	at org.planteome.samara.ScraperApsnet$.getTry(ScraperApsnet.scala:11)
	at org.planteome.samara.ScraperApsnet$.scrapeDiseases(ScraperApsnet.scala:27)
	at org.planteome.samara.ScraperApsnet$.scrape(ScraperApsnet.scala:17)
	at org.planteome.samara.Samara$.delayedEndpoint$org$planteome$samara$Samara$1(Samara.scala:42)
	at org.planteome.samara.Samara$delayedInit$body.apply(Samara.scala:6)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at org.planteome.samara.Samara$.main(Samara.scala:6)
	at org.planteome.samara.Samara.main(Samara.scala)
$ echo $?
1
